services:

  postgres:
    image: postgres:18
    container_name: chaos-theory-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chaos_theory_DB
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chaos_theory_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: chaos-theory-backend
    env_file:
      - ./backend/.docker.env
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: chaos-theory-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: